[package]
name = "rs_simple_utils"
version = "0.1.0"
edition = "2021"
auther = "sipu"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.6.0"
chrono = "0.4.38"
chrono-tz = "0.9.0"
reqwest = "0.12.4"
serde_json = "1.0.116"
winapi="0.3.9"