[package]
name = "rs_simple_utils"
version = "0.1.0"
edition = "2021"
auther = "sipu"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
chrono = "0.4.28"
chrono-tz = "0.8.3"
reqwest = "0.11.20"
serde_json = "1.0.105"
winapi="0.3.9"